// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB64vsAd7hfo22R0lGRob2cBkM9pXmajKY',
    appId: '1:764128780060:web:b6e6f4e5ff703aca9b24d9',
    messagingSenderId: '764128780060',
    projectId: 'gemini-quiz-app-45fa9',
    authDomain: 'gemini-quiz-app-45fa9.firebaseapp.com',
    storageBucket: 'gemini-quiz-app-45fa9.firebasestorage.app',
    measurementId: 'G-ZJ6Y3DDLWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5s05XM1VqYtilyRETwwJNWm13GzTIV0',
    appId: '1:764128780060:android:67567fcce6c0b9759b24d9',
    messagingSenderId: '764128780060',
    projectId: 'gemini-quiz-app-45fa9',
    storageBucket: 'gemini-quiz-app-45fa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPHDKfe7uxs5mXYjj2yJGk84KbniBqHuM',
    appId: '1:764128780060:ios:9fbb5e2d9e6dd9359b24d9',
    messagingSenderId: '764128780060',
    projectId: 'gemini-quiz-app-45fa9',
    storageBucket: 'gemini-quiz-app-45fa9.firebasestorage.app',
    iosClientId: '764128780060-77t734l0nb26nipo8c5pei4sb37is5fe.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.desafia',
  );

}